exports.up = knex =>
  knex.schema
    .createTableIfNotExists('moods', table => {
      table.increments('id').primary();
      table.text('uri').notNullable();
    })
    .then(() =>
      knex('moods').insert([
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/angel.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/crying.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/disappointed.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/dizzy.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/doubtful.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/dreaming.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/grinning.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/in-love.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/love-kiss.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/no-mouth.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/rolling-eyes.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/sleeping.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/smiling-devil.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/smiling.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/straight-face.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/surprised.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/thinking.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/tired.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/upside-down-smile.png',
        },
        {
          uri:
            'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/winking.png',
        },
      ]),
    )
    .then(() =>
      knex.schema.alterTable('users', t => {
        t.dropColumn('avatar');
        t.string('mood').defaultTo(
          'https://s3.eu-west-2.amazonaws.com/friendshipapp/moods/smiling.png',
        );
      }),
    );

exports.down = knex => knex.schema.table.dropTableIfExists('moods');
