const locations = [
  { name: 'Ahvenanmaa' },
  { name: 'Espoo' },
  { name: 'Helsinki' },
  { name: 'Hämeenlinna' },
  { name: 'Imatra' },
  { name: 'Joensuu' },
  { name: 'Jyväskylä' },
  { name: 'Kajaani' },
  { name: 'Kokkola' },
  { name: 'Kuopio' },
  { name: 'Lahti' },
  { name: 'Lappeenranta' },
  { name: 'Mikkeli' },
  { name: 'Oulu' },
  { name: 'Pietarsaari' },
  { name: 'Pori' },
  { name: 'Rovaniemi' },
  { name: 'Savonlinna' },
  { name: 'Seinäjoki' },
  { name: 'Tampere' },
  { name: 'Tornio' },
  { name: 'Turku' },
  { name: 'Vaasa' },
  { name: 'Vantaa' },
  { name: 'Kotka' },
  { name: 'Kouvola' },
];

exports.seed = knex => knex.insert(locations).into('locations');
